joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 2.0
    scale_linear_turbo:
      X: 4.0

    axis_angular:
      roll: 6
      pitch: 7
    scale_angular:
      roll: 2.0
      pitch: 2.0
    scale_angular_turbo:
      roll: 4.0
      pitch: 4.0

    enable_button: 4
    enable_turbo_button: 5

    require_enable_button: true